/**
 * Service worker registration.
 *
 * The worker itself is generated by Serwist from `src/app/sw.ts` at build time
 * and is not produced in development, so registration is skipped there.
 */

export const SERVICE_WORKER_URL = "/sw.js";

export async function registerServiceWorker(): Promise<void> {
  if (typeof navigator === "undefined" || !("serviceWorker" in navigator)) return;
  if (process.env.NODE_ENV !== "production") return;

  try {
    await navigator.serviceWorker.register(SERVICE_WORKER_URL, {
      scope: "/",
      // Always check the network for a new worker rather than a cached copy.
      updateViaCache: "none",
    });
  } catch (error) {
    // Registration failing only costs offline support; the app still works.
    console.warn("Offline support is unavailable", error);
  }
}
